# Docker

# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: Local
      #vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Stuart Docker Hub'
        repository: 'sfbowen/weatherapi'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
- stage: provision
  displayName: 'Terraforming on Azure'
  dependsOn: Build
  jobs:
  - job: Provision
    displayname: 'Provisoning container instance'
    pool:
      vmImage: 'ubuntu-latest'
    variables: 
    - group: TerraformSPVar
    steps:
    - script: |
        set -e 

        terraform init -input=false
        terraform apply -input=false -auto-approved
    name: 'RunTerraform'
    displayname: 'Run Terraform'
    env:
      ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
      ARM_TENANT_ID: $(ARM_TENANT_ID)
      ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
      TF_VAR_imagebuild: $(tag)
        

